# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find Interval
#' 
#' @param x A number 
#' @param cutpoints A sorted vector
#' 
#' @details
#' Elements of cutpoints represent endpoints
#' of adjacent intervals \eqn{[c_0,c_1)}, \eqn{[c_1,c_2)} ...,
#' \eqn{[c_{k},c_{k+1})}. Return the index \code{i} such that \code{x} is in 
#' \eqn{[c_i,c_{i+1})}; or return \code{-1} if \eqn{x < c_0}
#' or \code{k+1} if \eqn{x > c_{k+1}}
#'
#' @export
find_interval <- function(x, cutpoints) {
    .Call(`_DirectSampling_find_interval`, x, cutpoints)
}

#' Quantile Function for Discrete Distributions with Finite Support
#' 
#' @param q A vector of quantiles to compute
#' @param cp Vector of cumulative probabilities of distribution
#' 
#' @return 0-based indices corresponding to the \code{q} quantiles
#' 
#' @details
#' Compute quantiles of a discrete distribution with cumulative probabilities
#' \code{cp(0)}, \code{cp(1)}, ..., \code{cp(k-1)}. Return indices in
#' \eqn{\{ 0, 1, \ldots, k-1 \}} which represent the
#' \code{q} quantiles. The caller can then identify the corresponding value
#' of the distribution (of which this function does not need to be aware).
#' 
#' Uses a bisection search so support relatively large \code{k}.
#' 
#' Note that both \code{q} and \code{cp} may be given on the original
#' probability scale or the log-scale, as long as they are both on the same
#' scale.
#' @examples
#' # Create a simple distribution and compute cumulative probabilities
#' x_seq = 1:10
#' k = length(x_seq)
#' p = rep(1/k, k)
#' cp = cumsum(p)
#' 
#' xx = sample(x = x_seq, size = 100000, replace = TRUE, prob = p)
#' 
#' Compare empirical qq quantiles with q_discrete
#' qq = seq(0, 1, length.out = 100)
#' idx_calc = q_discrete(qq, cp)
#' x_emp = quantile(xx, probs = qq)
#' plot(x_emp, x_seq[idx_calc + 1])
#' 
#' Repeat calculation on the log-scale
#' idx_calc_log = q_discrete(log(qq), log(cp))
#' plot(idx_calc, idx_calc_log)
#' 
#' @export
q_discrete <- function(q, cp) {
    .Call(`_DirectSampling_q_discrete`, q, cp)
}

