# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcateg <- function(n, p) {
    .Call(`_DirectSampling_rcateg`, n, p)
}

#' @export
rcateg_mat <- function(P) {
    .Call(`_DirectSampling_rcateg_mat`, P)
}

#' @export
rcateg_logp <- function(n, logprob) {
    .Call(`_DirectSampling_rcateg_logp`, n, logprob)
}

#' @export
d_dgeom <- function(x, p, take_log) {
    .Call(`_DirectSampling_d_dgeom`, x, p, take_log)
}

#' @export
p_dgeom <- function(x, p) {
    .Call(`_DirectSampling_p_dgeom`, x, p)
}

#' @export
r_dgeom <- function(n, p) {
    .Call(`_DirectSampling_r_dgeom`, n, p)
}

#' @export
q_dgeom <- function(x, p) {
    .Call(`_DirectSampling_q_dgeom`, x, p)
}

#' @export
hi_dscnorm <- function(sigma, tol) {
    .Call(`_DirectSampling_hi_dscnorm`, sigma, tol)
}

#' @export
d_dscnorm <- function(x, sigma, tol = 1e-10, take_log = FALSE, normalize = TRUE) {
    .Call(`_DirectSampling_d_dscnorm`, x, sigma, tol, take_log, normalize)
}

#' @export
p_dscnorm <- function(x, sigma, tol = 1e-10) {
    .Call(`_DirectSampling_p_dscnorm`, x, sigma, tol)
}

#' @export
r_dscnorm <- function(n, sigma) {
    .Call(`_DirectSampling_r_dscnorm`, n, sigma)
}

#' @export
q_dscnorm <- function(q, sigma, tol = 1e-10) {
    .Call(`_DirectSampling_q_dscnorm`, q, sigma, tol)
}

#' @export
find_interval <- function(x, cutpoints) {
    .Call(`_DirectSampling_find_interval`, x, cutpoints)
}

#' @export
d_laplace <- function(x, mu, lambda, take_log) {
    .Call(`_DirectSampling_d_laplace`, x, mu, lambda, take_log)
}

#' @export
p_laplace <- function(x, mu, lambda) {
    .Call(`_DirectSampling_p_laplace`, x, mu, lambda)
}

#' @export
r_laplace <- function(n, mu, lambda) {
    .Call(`_DirectSampling_r_laplace`, n, mu, lambda)
}

#' @export
q_laplace <- function(x, mu, lambda) {
    .Call(`_DirectSampling_q_laplace`, x, mu, lambda)
}

#' @export
direct_sampler_lognormal_normal <- function(n, z, mu, sigma2, tau, tol, N, fill_method) {
    .Call(`_DirectSampling_direct_sampler_lognormal_normal`, n, z, mu, sigma2, tau, tol, N, fill_method)
}

#' @export
direct_sampler_lognormal_dscnorm <- function(n, z, mu, sigma2, tau, tol, N, fill_method) {
    .Call(`_DirectSampling_direct_sampler_lognormal_dscnorm`, n, z, mu, sigma2, tau, tol, N, fill_method)
}

#' @export
direct_sampler_lognormal_laplace <- function(n, z, mu, sigma2, lambda, tol, N, fill_method) {
    .Call(`_DirectSampling_direct_sampler_lognormal_laplace`, n, z, mu, sigma2, lambda, tol, N, fill_method)
}

#' @export
direct_sampler_lognormal_dgeom <- function(n, z, mu, sigma2, rho, tol, N, fill_method) {
    .Call(`_DirectSampling_direct_sampler_lognormal_dgeom`, n, z, mu, sigma2, rho, tol, N, fill_method)
}

#' @export
direct_sampler_normal_laplace <- function(n, z, mu, sigma2, lambda, tol, N, fill_method) {
    .Call(`_DirectSampling_direct_sampler_normal_laplace`, n, z, mu, sigma2, lambda, tol, N, fill_method)
}

#' @export
quadratic_roots <- function(A, B, C) {
    .Call(`_DirectSampling_quadratic_roots`, A, B, C)
}

#' @export
logsumprobs <- function(logprob) {
    .Call(`_DirectSampling_logsumprobs`, logprob)
}

